In [1]:
import requests
import csv

# Download the file from the URL
url = 'https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary/diabetes'
response = requests.get(url)
data = response.text

# Process the data from LIBSVM to CSV format
csv_data = []

# Parse each line
for line in data.strip().split('\n'):
    elements = line.split()
    
    # First element is the label (target value)
    label = elements[0]
    
    # Rest are feature:value pairs, we need to extract just the values
    features = {}
    for item in elements[1:]:
        index, value = item.split(':')
        features[int(index)] = value
    
    # Create a row for the CSV: [label, feature1, feature2, ..., featureN]
    row = [label] + [features.get(i, 0) for i in range(1, max(features.keys()) + 1)]
    csv_data.append(row)

# Save the data as a CSV file
csv_filename = 'diabetes.csv'
with open(csv_filename, mode='w', newline='') as file:
    writer = csv.writer(file)
    
    # Write headers (Label, Feature1, Feature2, ..., FeatureN)
    max_features = max([len(row) for row in csv_data]) - 1  # Minus 1 because the first column is the label
    header = ['Label'] + [f'Feature_{i}' for i in range(1, max_features + 1)]
    writer.writerow(header)
    
    # Write the data rows
    writer.writerows(csv_data)

print(f"File '{csv_filename}' has been saved.")

File 'diabetes.csv' has been saved.

In [2]:
url = 'https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary/diabetes_scale'
response = requests.get(url)
data = response.text

# Process the data from LIBSVM to CSV format
csv_data = []

# Parse each line
for line in data.strip().split('\n'):
    elements = line.split()
    
    # First element is the label (target value)
    label = elements[0]
    
    # Rest are feature:value pairs, we need to extract just the values
    features = {}
    for item in elements[1:]:
        index, value = item.split(':')
        features[int(index)] = value
    
    # Create a row for the CSV: [label, feature1, feature2, ..., featureN]
    row = [label] + [features.get(i, 0) for i in range(1, max(features.keys()) + 1)]
    csv_data.append(row)

# Save the data as a CSV file
csv_filename = 'diabetes_scale.csv'
with open(csv_filename, mode='w', newline='') as file:
    writer = csv.writer(file)
    
    # Write headers (Label, Feature1, Feature2, ..., FeatureN)
    max_features = max([len(row) for row in csv_data]) - 1  # Minus 1 because the first column is the label
    header = ['Label'] + [f'Feature_{i}' for i in range(1, max_features + 1)]
    writer.writerow(header)
    
    # Write the data rows
    writer.writerows(csv_data)

print(f"File '{csv_filename}' has been saved.")

File 'diabetes_scale.csv' has been saved.

In [3]:
# Load necessary libraries
from pandas.io.formats import printing
from torch.utils.data import Dataset, DataLoader
import pandas as pd
import torch
from sklearn.model_selection import train_test_split

In [6]:
# Load the dataset
df_1 = pd.read_csv('diabetes.csv')
df_1

,Label,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8
0,-1,6.0,148.0,72.0,35.0,0.0,33.599998,0.627,50.0
1,1,1.0,85.0,66.0,29.0,0.0,26.600000,0.351,31.0
2,-1,8.0,183.0,64.0,0.0,0.0,23.299999,0.672,32.0
3,1,1.0,89.0,66.0,23.0,94.0,28.100000,0.167,21.0
4,-1,0.0,137.0,40.0,35.0,168.0,43.099998,2.288,33.0
...,...,...,...,...,...,...,...,...,...
763,1,10.0,101.0,76.0,48.0,180.0,32.900002,0.171,63.0
764,1,2.0,122.0,70.0,27.0,0.0,36.799999,0.340,27.0
765,1,5.0,121.0,72.0,23.0,112.0,26.200001,0.245,30.0
766,-1,1.0,126.0,60.0,0.0,0.0,30.100000,0.349,47.0
767,1,1.0,93.0,70.0,31.0,0.0,30.400000,0.315,23.0

In [7]:
df_2 = pd.read_csv('diabetes_scale.csv')
df_2

,Label,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8
0,-1,-0.294118,0.487437,0.180328,-0.292929,-1.000000,0.001490,-0.531170,-0.033333
1,1,-0.882353,-0.145729,0.081967,-0.414141,-1.000000,-0.207153,-0.766866,-0.666667
2,-1,-0.058824,0.839196,0.049180,-1.000000,-1.000000,-0.305514,-0.492741,-0.633333
3,1,-0.882353,-0.105528,0.081967,-0.535354,-0.777778,-0.162444,-0.923997,-1.000000
4,-1,-1.000000,0.376884,-0.344262,-0.292929,-0.602837,0.284650,0.887276,-0.600000
...,...,...,...,...,...,...,...,...,...
763,1,0.176471,0.015075,0.245902,-0.030303,-0.574468,-0.019374,-0.920581,0.400000
764,1,-0.764706,0.226131,0.147541,-0.454545,-1.000000,0.096870,-0.776260,-0.800000
765,1,-0.411765,0.216080,0.180328,-0.535354,-0.735225,-0.219076,-0.857387,-0.700000
766,-1,-0.882353,0.266332,-0.016393,-1.000000,-1.000000,-0.102832,-0.768574,-0.133333
767,1,-0.882353,-0.065327,0.147541,-0.373737,-1.000000,-0.093890,-0.797609,-0.933333

In [2]:
import numpy as np

In [ ]:
class Perceptron(torch.nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.linear = torch.nn.Linear(input_dim, 1)

    def forward(self, x):
        return torch.sigmoid(self.linear(x))